name: blueshift_plugin
description: Fltter plugin for integrating Blueshift's native Android/iOS SDK to your Flutter app.
version: 0.0.2-beta
homepage: https://blueshift.com
repository: https://github.com/blueshift-labs/Blueshift-Flutter-Plugin
issue_tracker: https://github.com/blueshift-labs/Blueshift-Flutter-Plugin/issues
documentation: https://developer.blueshift.com/docs/install-and-set-up-flutter-plugin

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.blueshift.flutter.blueshift_plugin
        pluginClass: BlueshiftFlutterPlugin
      ios:
        pluginClass: BlueshiftFlutterPlugin
