// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYrwWSQ8ExtRz0_M2b_QN-3XmEDNWxvU',
    appId: '1:62519831960:android:92b0e8190f510831',
    messagingSenderId: '62519831960',
    projectId: 'blueshift-reads-app',
    databaseURL: 'https://blueshift-reads-app.firebaseio.com',
    storageBucket: 'blueshift-reads-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcUNLoOPsad0Y2T95SRtcDTXWKeOzIW1E',
    appId: '1:62519831960:ios:fca4a3c5568da0f9028fed',
    messagingSenderId: '62519831960',
    projectId: 'blueshift-reads-app',
    databaseURL: 'https://blueshift-reads-app.firebaseio.com',
    storageBucket: 'blueshift-reads-app.appspot.com',
    iosClientId: '62519831960-aa1m6pnhp0prsjc7nllsf0n4li4fl1u0.apps.googleusercontent.com',
    iosBundleId: 'com.blueshift.reads',
  );
}
